site_name: MyImagine Academy - Versio Graphics
site_url: https://graphics.myimagine.io/
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
 - Home : index.md
 - About : about_james_rivers.md
 - Downloads :  
   - "Course Syllabus" : downloads/211230-VER-GFX-AE.pdf
   - "Versio Operations Guide 4.6" : downloads/versio-operations-4.6.pdf
   - "AE Script DVE" : downloads/DVE.jsx
   - "AE Script RealTimeObject-2.1.0.46" : downloads/RealTimeObject-2.1.0.46.jsx
   - "AE Script RealTimeObject-2.1.0.47" : downloads/RealTimeObject-2.1.0.47.jsx
   - "AE Script RealTimeObject-2.1.0.48" : downloads/RealTimeObject-2.1.0.48.jsx
 - Versio Graphics Release Notes:
   - "Release Notes" : release_notes/202204281212_versio_grahics_release_notes.md
 - Chapter 1 - What is Versio Graphics?:
   - "Versio Graphics Overview" : chapter01_what_is_versio_graphics_and_how_they_are_used/2082386875_versio_graphics_overview_explanation.md
   - "Versio Creation Station" : chapter01_what_is_versio_graphics_and_how_they_are_used/2082457183_what_is_creation_station_explanation.md
   - "Versio Graphics Terminology" : chapter01_what_is_versio_graphics_and_how_they_are_used/2082416395_versio_graphics_terminology_reference.md
   - "Versio Graphics Data Sourcerer" : chapter01_what_is_versio_graphics_and_how_they_are_used/2083402020_what_is_data_sourcerer_explanation.md
   - "Versio EAS" : chapter01_what_is_versio_graphics_and_how_they_are_used/2083736539_what_is_eas_explanation.md
   - "Versio Basic Grpahics Creation" : chapter01_what_is_versio_graphics_and_how_they_are_used/2086642523_basic_graphics_creation_tutorial.md
   - "Straight or Premultiplied": chapter01_what_is_versio_graphics_and_how_they_are_used/exp_straight_premultiplied/202208031053_exp_straight_premultiplied.md
   - "Imagine Communications Tech Guide" : downloads/Versio Platform 4.6 System Operations_20211215.pdf
 - Chapter 2 - Veriso Creation Station :
   - "What is CSL" : chapter02_versio_ceation_station/2084363940_csl_review_explanation.md
   - "Best Practices" : chapter02_versio_ceation_station/2084300354_csl_best_practices_explanation.md
   - "CSL Support Formats" : chapter02_versio_ceation_station/2087262817_csl_supported_standards_formats_reference.md
   - "CSL Layout Management" : chapter02_versio_ceation_station/2087493295_csl_layout_management_tutorial.md
   - "CSL Create a new Layout" : chapter02_versio_ceation_station/2089219277_create_new_layout_howto.md
   - "CSL Add an object to a Layout" : chapter02_versio_ceation_station/2089386115_add_obects_to_layout_howto.md
   - "CSL Macros" : chapter02_versio_ceation_station/2092827666_csl_macros_tutorial.md
   - "CSL Realtime Content" : chapter02_versio_ceation_station/2093313703_csl_realtime_content_tutorial.md
   - "CSL Branded ++" : chapter02_versio_ceation_station/2100987628_csl_branded++_explanation.md
   - "Layout Z-Order" : chapter02_versio_ceation_station/tut_layout_z-order/202207181848_tut_layout_z-order.md
#- Chapter 3 - Operations (NA) :
 - Chapter 4 - After Effects :
   - "After Effects Set Up" : chapter04_getting_started_with_adobe_after_effects/2093924623_setup_after_effects_tutorial.md
   - "After Effects Trim Comps" : chapter04_getting_started_with_adobe_after_effects/202204281936_after_effect_trim_comps_tutorial.md
   - "After Effects Feature Guide" : chapter04_getting_started_with_adobe_after_effects/202204281741_after_effects_feature_support_guide_reference.md
   - "OTF or TTF Font Type?" : chapter04_getting_started_with_adobe_after_effects/ref_font_support/202206222141_ref_font_support.md
   - "After Effects Scripts Versions" : chapter04_getting_started_with_adobe_after_effects/202205051555_after_effects_rto_dve_scripts_version_reference.md
   - "After Effects Keyboard Shortcuts" : chapter04_getting_started_with_adobe_after_effects/keyboard_shortcuts/202205201340_keyboard_shortcuts.md
 - Chapter 5 - CTC Based Graphics :
   - "What is CTC?" : chapter05_create_ctc_based_graphics/2093968193_what_is_ctc_explanation.md
   - "CTC Cheat Sheet" : chapter05_create_ctc_based_graphics/2093970347_ctc_cheat_sheet_reference.md
   - "Create CTC Graphics" : chapter05_create_ctc_based_graphics/2094000644_create_ctc_create_ctc_graphics_howto.md
   - "AEP CTC RTO - BUG PROMO" : downloads/CH2_CTC_BUG_PROMO_2201.zip
 - Chapter 6 - RTO Based Graphics :
   - "What is RTO?" : chapter06_create_rto_based_graphics/2101008531_what_is_a_real_time_object_explanation.md
   - "Understanding RTO" : chapter06_create_rto_based_graphics/2101068464_rt_graphic_understanding_tutorial.md
   - "How to create RTO" : chapter06_create_rto_based_graphics/2101012022_creation_real_time_text_howto.md
   - "RTO in action" : chapter06_create_rto_based_graphics/2101011551_rto_in_action_tutorial.md
   - "Real Time Scrolls Crawls" : chapter06_create_rto_based_graphics/2114433994_creation_real_time_scrolls_crawls_howto.md
   - "Real Time GetData" : chapter06_create_rto_based_graphics/2114450932_realtime_getdata_tutorial.md
   - "Real Time ReQuery" : chapter06_create_rto_based_graphics/2114457656_realtime_requery_tutorial.md
   - "Real Time Pull" : chapter06_create_rto_based_graphics/202204272022_realtime_pull_data_tutorial.md
   - "Real Time ReQuery" : chapter06_create_rto_based_graphics/2114457656_realtime_requery_tutorial.md
   - "Real Time Clocks and Timers" : chapter06_create_rto_based_graphics/2114465112_creation_real_time_clocks_timers_howto.md
   - "Custom Variables" : chapter06_create_rto_based_graphics/tut_versio_graphics_variables/202207191158_tut_versio_graphics_variables.md
   - "AEP RTO SCROLLS" : downloads/CH6_RTO_SCROLL.aep
 - Chapter 7 - Create DVEs :
   - "Versio DVEs" : chapter07_create_dves/2122905693_dve_explanation.md
   - "DVE Creation Tutorial" : chapter07_create_dves/2122915384_dve_creation_understanding_tutorial.md
   - "DVE Creation How To" : chapter07_create_dves/2122916070_build_dve_howto.md
 - Chapter 8 - After Effects & Expressions :
   - "Learn Expressions" : chapter08_graphics_with_expressions/ref_expressions_after_effects_external_training/202207201155_ref_expressions_after_effects_external_training.md
   - "Example Expressions" : chapter08_graphics_with_expressions/202204282041_adobe_after_effects_expressions_reference.md
   - "Dynamic Width Review" : chapter08_graphics_with_expressions/tut_dynamic_text_width/202207201215_tut_dynamic_text_width.md
   - "AEP DYNAMIC WIDTH" : downloads/ch8_expression_dynamic_width.aep
#- Chapter 9 - Creation Clocks and Timers
#- Chapter 10 - Advanced Graphics
 - Chapter 11 - Data Sourcerer :
   - "About Data Sourcerer" : chapter11_datasourcer_install_config/exp_data_sourcerer/202207190825_exp_data_sourcerer.md
   - "Data Sourcer Install" : chapter11_datasourcer_install_config/tut_data_sourcerer_install/202207190834_tut_data_sourcerer_install.md
   - "Data Sourcerer Management" : chapter11_datasourcer_install_config/how_data_sourcerer_management/202206071553_how_data_sourcerer_management.md

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/images/favicon.png
  palette: 
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode


plugins:
    - search: {}
    - encryptcontent:
        global_password: 'Imagine2022!'
        remember_password: True
        default_expire_dalay: 12  
        password_button: True
        password_button_text: 'login'
        
extra:
  generator: false
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/james-rivers
      name: James Rivers on Twitter
  copyright: Copyright &copy; 2021 - 2022 James Rivers & MyImagine Academy Part of Imagine Communications.


