name: versio_graphics_mkdocs_publish
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install \
              mkdocs-material \
              mkdocs-encryptcontent-plugin \
              mkdocs-git-revision-date-localized-plugin \
              mkdocs-autolinks-plugin \
              mkdocs-section-index \
      - run: mkdocs gh-deploy --force
