name: versio_graphics_mkdocs_publish
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install \
              mkdocs-material \
              mkdocs-encryptcontent-plugin \
      - run: echo 'graphics.myimagine.io' > CNAME && mkdocs gh-deploy --force
